INSERT INTO PRODUCT (IDENTIFIER, NAME, PRICE) VALUES (1, 'bread', 49 );
INSERT INTO PRODUCT (IDENTIFIER, NAME, PRICE) VALUES (2, 'potatoes', 29 );
INSERT INTO PRODUCT (IDENTIFIER, NAME, PRICE) VALUES (3, 'juice', 69 );
INSERT INTO PRODUCT (IDENTIFIER, NAME, PRICE) VALUES (4, 'water', 35 );
INSERT INTO PRODUCT (IDENTIFIER, NAME, PRICE) VALUES (5, 'tomatoes', 139 );